
project_version : 0.1
project_author : "HMS-DBMI"
project_name : "Documentation"               # Project Name

documentation_directory : "./docs/" # Where output and other documentation files will live (temporarily).
output_directory : "./documentation/"

javascript_root_directory : "./src/encoded/static/components" # Fourfront JS directory

# Define what each section in nav-menu contains.
sections : [
    {
        "title" : "Getting Started",
        "path" : "./README.md",
        "order" : 0
    },
    {
        "title" : "Basic Usage",
        "path" : "./docs/usage.md"
    }
]
