# This is the default configuration.
# Please make a copy of this file and put it into your project's root directory,
# replacing any fields with your own values. Fields which are empty or nonexistant
# will be filled with the default values listed here.


project_version : 0.1
project_author : "HMS-DBMI"
project_name : "Sample Project To Document"  # Project Name

output_directory : "./documentation/"        # Save output here

python_project_directory : "./src/encoded/types"
javascript_root_directory : "./src/encoded/static/components/viz" # Fourfront JS directory

# Define what each section in nav-menu contains.
sections : [
    {
        "title" : "Getting Started",
        "path" : "./README.rst",
        "saveAs" : "getting-started.rst"
    },
    {
        "title" : "ElasticBeanstalk Deployment",
        "path" : "./docs/beanstalk-deployment.md",
        "saveAs" : "beanstalk-deployment.md"
    }
]
