
project_version : 0.1
project_author : "HMS-DBMI"
project_name : "Sample Project To Document"  # Project Name

documentation_directory : "./docs/"          # Where auxiliary static docs are located
output_directory : "./documentation/"        # Save output here

python_project_directory : "./src/encoded"
javascript_root_directory : "./src/encoded/static/components/viz" # Fourfront JS directory

# Define what each section in nav-menu contains.
sections : [
    {
        "title" : "Getting Started",
        "path" : "./README.md",
        "order" : 0
    },
    {
        "title" : "Basic Usage",
        "path" : "./docs/usage.md"
    },
    {
        "title": "PyDoc",
        "path" : "./docs/"
    }
]
